config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @product = Product.new
  end
  def new
    @product = Product.new
  end
  def create
    Product.create(product_params)
    redirect_to root_path
  end
  private
  def product_params
    params.require(:product).permit(:name, :brand, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="form">
<%= simple_form_for @product do |f| %>
  <%= f.input :name %>
  <%= f.input :brand %>
  <%= f.input :description %>
  <br />
  <%= f.submit 'Add product' %>
<% end %>
</div>

app/views/products/index.html.erb
<div class="row">
<% @products.each do |product| %>
<h1><%= product.name %></h1>
<h2>- <%= product.brand %></h2>
<h2><%= product.description %></h2>
<% end %>
</div>
<h1><%= link_to 'Add a New Product', new_product_path %></h1>
<%= render :partial => "form" %>

app/views/products/new.html.erb
<h1>Add a new product</h1>
<%= render :partial => "form" %>